/** @type {import('tailwindcss').Config} */
// Design tokens merged from all 38 original HTML screens of the
// "What Should We Eat? / Dastarkhān" prototype so every converted
// page keeps pixel-identical colors, spacing, radii and type.
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  // Every class this app uses appears as a literal string in a template or in
  // a page's .ts (the classList.add/toggle calls), both of which the `content`
  // glob above scans -- so normal purging is safe. Do not re-add a catch-all
  // safelist: it emitted the entire utility universe as a 12 MB stylesheet.
  theme: {
    extend: {
      colors: {
        background: "#fdf8f5",
        "cream-background": "#FFFDF9",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f4f0ec",
        "inverse-primary": "#e2c382",
        "inverse-surface": "#31302e",
        "on-background": "#1c1b1a",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#463300",
        "on-primary-fixed": "#261a00",
        "on-primary-fixed-variant": "#59440f",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6f6349",
        "on-secondary-fixed": "#221b07",
        "on-secondary-fixed-variant": "#50462e",
        "on-surface": "#1c1b1a",
        "on-surface-variant": "#4d463a",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#313824",
        "on-tertiary-fixed": "#171e0b",
        "on-tertiary-fixed-variant": "#424a34",
        outline: "#7e7668",
        "outline-variant": "#d0c5b5",
        primary: "#735b25",
        "primary-container": "#b89b5e",
        "primary-fixed": "#ffdf9e",
        "primary-fixed-dim": "#e2c382",
        secondary: "#695d44",
        "secondary-container": "#f1e1c0",
        "secondary-fixed": "#f1e1c0",
        "secondary-fixed-dim": "#d4c5a6",
        "soft-border": "#E8E2D9",
        surface: "#fdf8f5",
        "surface-bright": "#fdf8f5",
        "surface-container": "#f1ede9",
        "surface-container-high": "#ece7e4",
        "surface-container-highest": "#e6e2de",
        "surface-container-low": "#f7f3ef",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#ddd9d6",
        "surface-tint": "#735b25",
        "surface-variant": "#e6e2de",
        tertiary: "#5a614a",
        "tertiary-container": "#9aa287",
        "tertiary-fixed": "#dee6c8",
        "tertiary-fixed-dim": "#c2caad",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "section-gap": "48px",
        gutter: "16px",
        "container-padding": "24px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display Variable", "Playfair Display", "serif"],
        display: ["Playfair Display Variable", "Playfair Display", "serif"],
        "headline-lg": ["Playfair Display Variable", "Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display Variable", "Playfair Display", "serif"],
        "headline-md": ["Playfair Display Variable", "Playfair Display", "serif"],
        "title-lg": ["Inter Variable", "Inter", "sans-serif"],
        "body-lg": ["Inter Variable", "Inter", "sans-serif"],
        "body-md": ["Inter Variable", "Inter", "sans-serif"],
        body: ["DM Sans Variable", "DM Sans", "sans-serif"],
        "label-lg": ["Inter Variable", "Inter", "sans-serif"],
        "label-sm": ["Inter Variable", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
